# SPDX-FileCopyrightText: 2026 TraceGuard contributors
# SPDX-License-Identifier: Apache-2.0

packages:
  - apps/*
  - packages/*
allowBuilds:
  "@swc/core": true
  esbuild: true
  protobufjs: true
overrides:
  "@esbuild-kit/core-utils>esbuild": 0.25.0
