# SPDX-FileCopyrightText: 2026 TraceGuard contributors
# SPDX-License-Identifier: Apache-2.0

packages:
  - apps/*
  - packages/*
allowBuilds:
  "@swc/core": true
  sharp: true
overrides:
  postcss: 8.5.19
